import { config } from "dotenv";

config();

export const { PORT, DB_URI, CLOUDINARY_API_KEY, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_SECRET, ACCESS_TOKEN_JWT_SECRET, ACCESS_TOKEN_JWT_EXPIRES_IN } =
	process.env;
